{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOywQg/5755jiCAfJkOrUyI",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/erickaleed/fuzzy-pancake/blob/main/DeMaria_lab09_1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2oliHmciF9_x",
        "outputId": "68b32a5e-98d2-4180-c00f-8f73527c5afb"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Player 1 was dealt 4 of Hearts\n",
            "Player 2 was dealt Queen of Diamonds\n",
            "Player 1 was dealt Queen of Hearts\n",
            "Player 2 was dealt 6 of Spades\n",
            "Player 1 was dealt Ace of Clubs\n",
            "Player 2 was dealt 2 of Clubs\n",
            "Player 1 was dealt 8 of Spades\n",
            "Player 2 was dealt Queen of Clubs\n",
            "No winner.\n",
            "\n",
            "Press Enter for next game...\n",
            "Player 1 was dealt 9 of Diamonds\n",
            "Player 2 was dealt 10 of Diamonds\n",
            "Player 1 was dealt Ace of Spades\n",
            "Player 2 was dealt Jack of Clubs\n",
            "Player 1 was dealt 9 of Hearts\n",
            "Player 2 was dealt 9 of Clubs\n",
            "No winner.\n",
            "\n",
            "Press Enter for next game...\n",
            "Player 1 was dealt 2 of Diamonds\n",
            "Player 2 was dealt 8 of Diamonds\n",
            "Player 1 was dealt 3 of Diamonds\n",
            "Player 2 was dealt 6 of Diamonds\n",
            "Player 1 was dealt 7 of Hearts\n",
            "Player 2 was dealt 9 of Spades\n",
            "Player 1 wins.\n",
            "\n",
            "Press Enter for next game...\n",
            "Player 1 was dealt 5 of Hearts\n",
            "Player 2 was dealt 10 of Spades\n",
            "Player 1 was dealt 4 of Diamonds\n",
            "Player 2 was dealt 4 of Spades\n",
            "Player 1 was dealt King of Clubs\n",
            "Player 2 was dealt 6 of Clubs\n",
            "Player 1 was dealt Ace of Hearts\n",
            "Player 2 was dealt Ace of Diamonds\n",
            "Player 1 was dealt 3 of Clubs\n",
            "Player 2 was dealt King of Spades\n",
            "No winner.\n",
            "\n",
            "Press Enter for next game...\n",
            "Player 1 was dealt 7 of Spades\n",
            "Player 2 was dealt 8 of Hearts\n",
            "Player 1 was dealt King of Diamonds\n",
            "Player 2 was dealt 4 of Clubs\n",
            "Player 1 was dealt 3 of Spades\n",
            "Player 2 was dealt 5 of Spades\n",
            "Player 1 was dealt 5 of Clubs\n",
            "Player 2 was dealt 7 of Clubs\n",
            "No winner.\n",
            "\n",
            "Press Enter for next game...\n",
            "Player 1 was dealt 10 of Hearts\n",
            "Player 2 was dealt Jack of Hearts\n",
            "Player 1 was dealt 7 of Diamonds\n",
            "Player 2 was dealt Queen of Spades\n",
            "Player 1 was dealt 3 of Hearts\n",
            "Player 2 was dealt 2 of Hearts\n",
            "Player 1 wins.\n",
            "\n",
            "Press Enter for next game...\n",
            "Player 1 was dealt Jack of Spades\n",
            "Player 2 was dealt 5 of Diamonds\n",
            "Player 1 was dealt 10 of Clubs\n",
            "Player 2 was dealt 2 of Spades\n",
            "Player 1 was dealt 6 of Hearts\n",
            "Player 2 was dealt Jack of Diamonds\n",
            "Player 2 wins.\n",
            "\n"
          ]
        }
      ],
      "source": [
        "# Ericka-Lee DeMaria | August 31, 2025 | DeMaria_lab09-1.py\n",
        "# Purpose: Simulate simplified blackjack using dictionaries and control structures.\n",
        "\n",
        "import random\n",
        "\n",
        "def create_deck():\n",
        "    ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King', 'Ace']\n",
        "    suits = ['Hearts', 'Diamonds', 'Clubs', 'Spades']\n",
        "    return [(rank, suit) for rank in ranks for suit in suits]\n",
        "\n",
        "def card_value(card, current_total):\n",
        "    rank = card[0]\n",
        "    if rank in ['Jack', 'Queen', 'King']:\n",
        "        return 10\n",
        "    elif rank == 'Ace':\n",
        "        return 11 if current_total + 11 <= 21 else 1\n",
        "    else:\n",
        "        return int(rank)\n",
        "\n",
        "def play_game(deck):\n",
        "    player_scores = {'Player 1': 0, 'Player 2': 0}\n",
        "    hands = {'Player 1': [], 'Player 2': []}\n",
        "    totals = {'Player 1': 0, 'Player 2': 0}\n",
        "    game_over = False\n",
        "\n",
        "    while not game_over and len(deck) >= 2:\n",
        "        for player in ['Player 1', 'Player 2']:\n",
        "            card = deck.pop()\n",
        "            hands[player].append(card)\n",
        "            value = card_value(card, totals[player])\n",
        "            totals[player] += value\n",
        "            print(f\"{player} was dealt {card[0]} of {card[1]}\")\n",
        "            if totals[player] > 21:\n",
        "                game_over = True\n",
        "\n",
        "    if totals['Player 1'] <= 21 and totals['Player 2'] > 21:\n",
        "        print(\"Player 1 wins.\\n\")\n",
        "        player_scores['Player 1'] += 1\n",
        "    elif totals['Player 2'] <= 21 and totals['Player 1'] > 21:\n",
        "        print(\"Player 2 wins.\\n\")\n",
        "        player_scores['Player 2'] += 1\n",
        "    elif totals['Player 1'] <= 21 and totals['Player 2'] <= 21:\n",
        "        if totals['Player 1'] > totals['Player 2']:\n",
        "            print(\"Player 1 wins.\\n\")\n",
        "            player_scores['Player 1'] += 1\n",
        "        elif totals['Player 2'] > totals['Player 1']:\n",
        "            print(\"Player 2 wins.\\n\")\n",
        "            player_scores['Player 2'] += 1\n",
        "        else:\n",
        "            print(\"It's a tie.\\n\")\n",
        "    else:\n",
        "        print(\"No winner.\\n\")\n",
        "\n",
        "    return player_scores\n",
        "\n",
        "def main():\n",
        "    deck = create_deck()\n",
        "    random.shuffle(deck)\n",
        "    total_scores = {'Player 1': 0, 'Player 2': 0, 'Ties': 0}\n",
        "\n",
        "    while len(deck) >= 6:\n",
        "        scores = play_game(deck)\n",
        "        for player in ['Player 1', 'Player 2']:\n",
        "            total_scores[player] += scores[player]\n",
        "        input(\"Press Enter for next game...\")\n",
        "\n",
        "    print(\"\\nAll cards dealt ******\")\n",
        "    print(f\"Player 1 won {total_scores['Player 1']} games\")\n",
        "    print(f\"Player 2 won {total_scores['Player 2']} games\")\n",
        "    print(f\"There were {total_scores['Ties']} tie games\")\n",
        "\n",
        "main()\n"
      ]
    }
  ]
}